export const skillsContent = {
  primary: [
    {
      color: '#00CDFE',
      icon: 'FaReact',
      iconFamily: 'Fa',
      label: 'React',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#D84925',
      icon: 'FaHtml5',
      iconFamily: 'Fa',
      label: 'HTML',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#EBD51D',
      icon: 'SiJavascript',
      iconFamily: 'Si',
      label: 'JavaScript',
      shadowSize: 18,
      size: 64,
      sizeWrapper: 82,
    },
    {
      color: '',
      icon: '',
      iconFamily: '',
      label: 'C#',
      shadowSize: 18,
      size: 0,
      sizeWrapper: 82,
      svgRef: 'CSharp',
    },
    {
      color: '#EBD51D',
      icon: 'SiStyledcomponents',
      iconFamily: 'Si',
      label: 'Styled Components',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#E0E0E0',
      icon: 'SiPostgresql',
      iconFamily: 'Si',
      label: 'PostgreSQL',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
  ],
  secondary: [
    {
      color: '#3CAF7C',
      icon: 'FaVuejs',
      iconFamily: 'Fa',
      label: 'Vue',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#2449D9',
      icon: 'FaCss3Alt',
      iconFamily: 'Fa',
      label: 'CSS',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#F2437E',
      icon: 'SiStorybook',
      iconFamily: 'Si',
      label: 'Storybook',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#E0E0E0',
      icon: 'FaUnity',
      iconFamily: 'Fa',
      label: 'Unity',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#E11420',
      icon: 'GoRuby',
      iconFamily: 'Go',
      label: 'Ruby on Rails',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
    {
      color: '#00E161',
      icon: 'SiMongodb',
      iconFamily: 'Si',
      label: 'MongoDB',
      shadowSize: 18,
      size: 70,
      sizeWrapper: 82,
    },
  ],
};
